include: package:flutter_lints/flutter.yaml
linter:
analyzer: 
  errors:
   always_declare_return_types: error
   unnecessary_await_in_return: error
   
  rules:
    always_declare_return_types: true
    avoid_unused_constructor_parameters: true
    prefer_single_quotes: true
    prefer_final_locals: true
    unnecessary_await_in_return: true

