name: tell_craft
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Carousel1.png 
    - assets/images/Carousel2.png
    - assets/images/Carousel3.png
    - assets/images/miniclock.png
    - assets/images/personLogo.png
    - assets/images/tellCraft.png
    

