name: tell_craft
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  provider: ^6.0.5
  validatorless: ^1.2.3

flutter_native_splash:
  image: assets/app/logo.png
  color: "#000000"
  android: true
  ios: true
  android_disable_fullscreen: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_spinkit: ^5.1.0
  http: ^0.13.5
  animated_text_kit: ^4.2.2

  firebase_database: ^10.2.5
  firebase_core_platform_interface: ^4.8.0
  pdf: ^3.3.0
  image_picker: ^0.8.3+2
  path_provider: ^2.0.2
  syncfusion_flutter_pdfviewer: ^20.4.54
  share: ^2.0.4


  # https://pub.dev/packages/firebase_core

  # https://pub.dev/packages/firebase_auth
  firebase_auth: ^4.9.0

  # https://pub.dev/packages/google_sign_in
  google_sign_in: ^6.1.5

  # https://pub.dev/packages/cloud_firestore

  # https://pub.dev/packages/firebase_storage
  firebase_storage: ^11.2.6


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/app/
    

